'Autogenerated code by xlwings - changes will be lost with next import!
#Const App = "Microsoft Excel" 'Adjust when using outside of Excel
Function double_sum(x, y)
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        double_sum = XLPy.CallUDF("well_situation", "double_sum", Array(x, y), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        double_sum = XLPy.CallUDF("well_situation", "double_sum", Array(x, y))
        Exit Function
    #End If
failed:
    double_sum = Err.Description
End Function

Function get_wellinfo(Optional factor)
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        get_wellinfo = XLPy.CallUDF("well_situation", "get_wellinfo", Array(factor), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        get_wellinfo = XLPy.CallUDF("well_situation", "get_wellinfo", Array(factor))
        Exit Function
    #End If
failed:
    get_wellinfo = Err.Description
End Function

Function hello(name)
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        hello = XLPy.CallUDF("well_situation", "hello", Array(name), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        hello = XLPy.CallUDF("well_situation", "hello", Array(name))
        Exit Function
    #End If
failed:
    hello = Err.Description
End Function

Function ret_test()
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        ret_test = XLPy.CallUDF("well_situation", "ret_test", Array(), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        ret_test = XLPy.CallUDF("well_situation", "ret_test", Array())
        Exit Function
    #End If
failed:
    ret_test = Err.Description
End Function

Function sum_and_product(number1, number2)
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        sum_and_product = XLPy.CallUDF("well_situation", "sum_and_product", Array(number1, number2), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        sum_and_product = XLPy.CallUDF("well_situation", "sum_and_product", Array(number1, number2))
        Exit Function
    #End If
failed:
    sum_and_product = Err.Description
End Function

