Attribute VB_Name = "xlwings_udfs"
'Autogenerated code by xlwings - changes will be lost with next import!
#Const App = "Microsoft Excel" 'Adjust when using outside of Excel
Function double_sum(x, y)
Attribute double_sum.VB_Description = "Returns twice the sum of the two arguments"
Attribute double_sum.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        double_sum = XLPy.CallUDF("well_situation", "double_sum", Array(x, y), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        double_sum = XLPy.CallUDF("well_situation", "double_sum", Array(x, y))
        Exit Function
    #End If
failed:
    double_sum = Err.Description
End Function

Function get_wellinfo(Optional factor)
Attribute get_wellinfo.VB_Description = "Python function 'get_wellinfo' defined in 'd:\\05_send\\pythonproject\\well_situation\\well_situation.py'."
Attribute get_wellinfo.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        get_wellinfo = XLPy.CallUDF("well_situation", "get_wellinfo", Array(factor), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        get_wellinfo = XLPy.CallUDF("well_situation", "get_wellinfo", Array(factor))
        Exit Function
    #End If
failed:
    get_wellinfo = Err.Description
End Function

Function hello(name)
Attribute hello.VB_Description = "Python function 'hello' defined in 'd:\\05_send\\pythonproject\\well_situation\\well_situation.py'."
Attribute hello.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        hello = XLPy.CallUDF("well_situation", "hello", Array(name), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        hello = XLPy.CallUDF("well_situation", "hello", Array(name))
        Exit Function
    #End If
failed:
    hello = Err.Description
End Function

Function ret_test()
Attribute ret_test.VB_Description = "Python function 'ret_test' defined in 'd:\\05_send\\pythonproject\\well_situation\\well_situation.py'."
Attribute ret_test.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        ret_test = XLPy.CallUDF("well_situation", "ret_test", Array(), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        ret_test = XLPy.CallUDF("well_situation", "ret_test", Array())
        Exit Function
    #End If
failed:
    ret_test = Err.Description
End Function

Function sum_and_product(number1, number2)
Attribute sum_and_product.VB_Description = "Python function 'sum_and_product' defined in 'd:\\05_send\\pythonproject\\well_situation\\well_situation.py'."
Attribute sum_and_product.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        sum_and_product = XLPy.CallUDF("well_situation", "sum_and_product", Array(number1, number2), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        sum_and_product = XLPy.CallUDF("well_situation", "sum_and_product", Array(number1, number2))
        Exit Function
    #End If
failed:
    sum_and_product = Err.Description
End Function

